---
title: "Code to reproduce your simulation"
output: pdf_document
params:
  date: !r Sys.Date()
  j: NA
  jm: NA
  sm: NA
  nu: NA
  num: NA
  ext: NA
  trait_sigma: NA
  env_sigma: NA
  comp_sigma: NA
  m: NA
  mu: NA
  eq: NA
  bp: NA
  type: NA
  iter: NA
---
## Load roleR package

```{r, echo=FALSE, message=FALSE}
library(here)
```

```{r,eval=FALSE}
library(roleR)
```


## Parameters

These are the input parameters necessary to reproduce your simulation.  



```{r, echo=FALSE}
# make templates for several different chunks, e.g. making params, runing model
temp <- readLines(here("inst", "templates", "params.txt"), warn = FALSE)
x <- sprintf(paste(temp, collapse = '\n'), 
             params$j,
             params$jm,
             params$sm,
             params$nu,
             params$num,
             params$ext,
             params$trait_sigma,
             params$env_sigma,
             params$comp_sigma,
             params$m,
             params$mu,
             params$eq,
             params$bp,
             params$type,
             params$iter
             )

temp_params <- tempfile("role_params", fileext = ".R")

writeLines(x, temp_params)
```

```{r code=readLines(temp_params), eval = FALSE}
```


You can run your model either as a `roleModel` for single models or `roleExperiment` for multiple models . Here, we're using `roleExperiment`. 

```{r, eval=FALSE}
role_experiment <- roleExperiment(list(role_params))
```



